### ISSUE TITLE
Android Java Class Error

### ISSUE THREAD

**Issue by ynsbalci** [zs9024/UnityRTC#1]
webRtcSDK_instance = new AndroidJavaClass("com.wow.mutiaudiortc.RtcSdk");

java class not found! how can ı import?
 is it our special class or libwebrtc ?

**Comment by zs9024** [comment]
how do you use the MutiRTC_Unity?
the runtime platform must be andorid or ios ,if you want to test it ,you have to build an apk at first ,and then run  on mobile phone
the "com.wow.mutiaudiortc.RtcSdk" is java class ,in "Plugins\Android\AudioRtc\libs\mutiaudiortc.jar"

**Comment by ynsbalci** [comment]
its working with android tahnk you!
but ı have a other question 
which node version you used, ı cahnge some codes! (because not work a ubuntu 16 lts)

**Comment by zs9024** [comment]
v6.9.5  my SignalServer(node) is working with windows
with ubantu maybe you need  to install the modules restart ,but i'm not sure
